name: Publish module version
# triggered by a dev updating the terraform module
# almost exclusively because the underlying cloudformation template has updated
# and we want to match version with that, which may or may not require a functionality change
# so there is currently a version mismatch
# dev needs to determine whether code changes are needed in module

on:
  workflow_dispatch:
  push:
    branches:
      - dummy

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # check for updated modules/directories
      # perhaps limit to single, or process multiple in matrix?
      # use hellofresh action?
      - name: Check for updated modules
        run: echo 'check for updates'

      # pull out version number for that module
      - name: Find module version number
        run: echo 'find module version'

      # check if tag exists for that version
      - name: Check for version tag
        run: echo 'check version tag'

      # create tag and push
      - name: Create version tag
        run: echo 'create version tag'
